multiple fixs and improvements

diff --git a/dc_pp b/dc_pp
--- a/dc_pp
+++ b/dc_pp
@@ -20,6 +20,8 @@ INTERACTIVE='Yes'
 QUIET_OPTION_1=1 # post-procesado completo siempre
 QUIET_OPTION_2=1 # Blanco y negro (1bit)
 QUIET_OPTION_3=1 # si existe sobreescribir PDF
+POST_ACTIONS_ENABLED='No'
+PDFBEADS_LAYOUT=''
 
 # --- process param
 
@@ -52,6 +54,15 @@ while [ $# -ne 0 ]
             ;;
         title=*)
             PROJECT_TITLE="${arg#*=}"
+            ;;
+        include=*)
+            INCLUDE_LIST="${arg#*=}"
+            ;;
+        post-actions-enabled)
+            POST_ACTIONS_ENABLED='Yes'
+            ;;
+        pdf-layout=*)
+            PDFBEADS_LAYOUT="${arg#*=}"
             ;;
         quiet)
             INTERACTIVE="No"
@@ -103,22 +114,29 @@ EXT="jpg,JPG,tif,TIF,jpeg,JPEG,TIFF,tiff"
 
 PROFILE_OPTIONS=''
 
+if [ "$INCLUDE_LIST" != "" ]
+  then
+    echo "Sólo se procesarán los siguientes ítems: '$INCLUDE_LIST'"
+    IFS="," read -ra tmpArr <<< "0004,0005,0006,0007"
+    nItems=$(${#tmpArr[@]})
+fi
+
 # --- check prior execution
 
 if [ -d "$DONEPATH/.processing" ]
   then
     echo ""
-    if find "$DONEPATH/.processing" -maxdepth 1 -name "*.tif" | grep -q .
+    if find "$DONEPATH/.processing" -mindepth 1 -maxdepth 1 -name "*.tif" | grep -q .
       then
         PREV_SC="Yes"
         echo " - Posibles archivos de un post-procesamiento previo detectados: Scantailor."
     fi
-    if find "$DONEPATH/.processing" -maxdepth 1 -name "*.html" | grep -q .
+    if find "$DONEPATH/.processing" -mindepth 1 -maxdepth 1 -name "*.html" | grep -q .
       then
         PREV_OCR="Yes"
         echo " - Posibles archivos de un post-procesamiento previo detectados: OCR."
     fi
-    if find "$DONEPATH/.processing" -maxdepth 1 -name "*.jbig2" | grep -q .
+    if find "$DONEPATH/.processing" -mindepth 1 -maxdepth 1 -name "*.jbig2" | grep -q .
       then
         PREV_PDFB="Yes"
         echo " - Posibles archivos de un post-procesamiento previo detectados: PDFBeads."
@@ -184,15 +202,16 @@ case "$option" in
      ;;
   1)
      CREATE_SYMLINKS_IN_ALL_DIR="Forced" # solo evita que vuelva a preguntar que hacer mas adelante
+     PARAM="$PARAM pdfbeads-force"
      ;;
   2)
      CREATE_SYMLINKS_IN_ALL_DIR="Forced"
-     PARAM="$PARAM no-ocr"
+     PARAM="$PARAM no-ocr pdfbeads-force"
      ;;
   3)
      if [ "$PREV_SC" == "Yes" ] 
      then 
-       PARAM="no-scantailor reoptimize-pdf"
+       PARAM="no-scantailor " # reoptimize-pdf (Re-procesar SOLO el OCR, para que reoptimizar?)
        CREATE_SYMLINKS_IN_ALL_DIR="No"
        if [ "$PREV_PDFB" == "Yes" ]; then PARAM="no-scantailor"; fi
      else
@@ -261,7 +280,7 @@ esac
 if [ "$CREATE_SYMLINKS_IN_ALL_DIR" != "No" ]
   then
    # delete symliks if any
-   if find "$ALLPATH" -mindepth 1 -print -quit | grep -q .
+   if find "$ALLPATH" -maxdepth 1 -print -quit | grep -q .
     then
       if [ "$CREATE_SYMLINKS_IN_ALL_DIR" == "Yes" ]
        then
@@ -308,28 +327,52 @@ if [ "$CREATE_SYMLINKS_IN_ALL_DIR" != "No" ]
     then
 
       # create symlinks form 'odd' and 'even' in 'all'
-      if find "$EVENPATH" -mindepth 1 -name "test.jpg" | grep -q .
+      if find "$EVENPATH" -maxdepth 1 -name "test.jpg" | grep -q .
        then
-        rm "$EVENPATH/test.jpg" && echo " - se eliminó el archivo de prueba 'test.jpg' de '$EVENPATH'" || exit 1
+        rm "$EVENPATH/test.jpg" && echo " - se eliminó el archivo de prueba 'test.jpg' de '$EVENPATH'" || { echo "Debug: 01"; exit 1; }
       fi
-      if find "$ODDPATH" -mindepth 1 -name "test.jpg" | grep -q .   
+      if find "$ODDPATH" -maxdepth 1 -name "test.jpg" | grep -q .  
        then
-        rm "$ODDPATH/test.jpg" && echo " - se eliminó el archivo de prueba 'test.jpg' de '$ODDPATH'" || exit 1
+        rm "$ODDPATH/test.jpg" && echo " - se eliminó el archivo de prueba 'test.jpg' de '$ODDPATH'" || { echo "Debug: 02"; exit 1; }
       fi
 
-      echo -n " Creando symlinks en '$ALLPATH'.."         
-      find "$EVENPATH" -maxdepth 1 -type f -exec ln -s {} "$ALLPATH" \; && echo -n "OK .." || { echo " ERROR al intentar crear symlinks desde '$EVENPATH'"; exit 1; }
-      find "$ODDPATH" -maxdepth 1 -type f -exec ln -s {} "$ALLPATH" \; &&  echo " OK" || { echo " ERROR al intentar crear symlinks desde '$ODDPATH'"; exit 1; }
+      echo " Creando symlinks en '$ALLPATH'.."
+      find "$EVENPATH" -mindepth 1 -maxdepth 1 -type f -exec ln -s {} "$ALLPATH" \; && echo -n "OK .." || { echo " ERROR al intentar crear symlinks desde '$EVENPATH'"; exit 1; }
+      find "$ODDPATH" -mindepth 1 -maxdepth 1 -type f -exec ln -s {} "$ALLPATH" \; &&  echo " OK" || { echo " ERROR al intentar crear symlinks desde '$ODDPATH'"; exit 1; }
 
    fi  
 fi
 
+if [ "$INCLUDE_LIST" != "" ]
+  then
+    INCLUDE="include=$INCLUDE_LIST"
+    PARAM=$PARAM" pdfbeads-holds-procfiles"
+fi
+
+if [ "$PDFBEADS_LAYOUT" != "" ]
+  then
+    layouts=(SinglePage OneColumn TwoColumnLeft TwoColumnRight TwoPageLeft TwoPageRight)
+    if [[ " ${layouts[@]} " =~ " ${PDFBEADS_LAYOUT} " ]]
+      then
+        PARAM="$PARAM pdf-layout=$PDFBEADS_LAYOUT"
+        echo " PDF layout: '$PDFBEADS_LAYOUT'"
+    fi
+fi
+
+PARAM="$PARAM scantailor-output-project"
+            
 # --- profile-processor
 
 echo " Enviar acción a la cola de procesamiento..."
 echo ""
 
-$SEND_CMD "$PROFILE_PROCESSOR 'src=$ALLPATH' 'wrk=$DONEPATH' 'log=$LOGPATH' ext=$EXT $PARAM 'name=$OUTPUT_NAME' profile=a3$PROFILE_OPTIONS debug scantailor-verbose && $POST_ACTIONS_SCRIPT 'project=$PROJECT_PATH' 'title=$PROJECT_TITLE' 'done=$DONEPATH' 'name=$OUTPUT_NAME' 'output_path=$DONEPATH/$OUTPUT_NAME' #$PROJECT_PATH"
+if [ "$POST_ACTIONS_ENABLED" == "Yes" ]
+ then
+   $SEND_CMD "$PROFILE_PROCESSOR 'src=$ALLPATH' 'wrk=$DONEPATH' 'log=$LOGPATH' ext=$EXT $PARAM 'name=$OUTPUT_NAME' $INCLUDE profile=a3$PROFILE_OPTIONS debug pretty-format && $POST_ACTIONS_SCRIPT 'project=$PROJECT_PATH' 'title=$PROJECT_TITLE' 'done=$DONEPATH' 'name=$OUTPUT_NAME' 'output_path=$DONEPATH/$OUTPUT_NAME' #$PROJECT_PATH $nItems"
+else
+   $SEND_CMD "$PROFILE_PROCESSOR 'src=$ALLPATH' 'wrk=$DONEPATH' 'log=$LOGPATH' ext=$EXT $PARAM 'name=$OUTPUT_NAME' $INCLUDE profile=a3$PROFILE_OPTIONS debug pretty-format #$PROJECT_PATH $nItems"
+fi
+
 
 if [ $? -eq 0 ]
 then
